apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderdeployment
spec:
  selector:
    matchLabels:
      app: order
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - image: us.icr.io/YOUR_CONTAINER_REGISTRY_NAMESPACE/order:1.0
        name: order
        imagePullPolicy: Always
        ports:
        - containerPort: 9003            
      restartPolicy: Always
