apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservicedeployment
spec:
  selector:
    matchLabels:
      app: orderservice
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
      - image: us.icr.io/tt-lab-project/laborderservice:1.0
        name: orderservice
        imagePullPolicy: Always
        ports:
        - containerPort: 9743
        env:
          - name: menuServiceEndpoint.endpoint
            valueFrom:
              configMapKeyRef:
                name: orderservicecm
                key: menuServiceEndpoint.endpoint
      restartPolicy: Always